# Rockchip RK3368 GeekBox
BOARD_NAME="GeekBox"
BOARDFAMILY="rockchip64"
BOOT_SOC="rk3368"
BOOT_SCENARIO="trusted"
ATF_COMPILE="yes"
EXTENSION_UBOOT_FIX_PYLIBFDT="yes"
UBOOT_CUSTOM_POSTPROCESS="no"
BOOTCONFIG="geekbox_defconfig"
BOOTBRANCH="edge"
KERNEL_TARGET="current,edge"
FDTFILE="rockchip/rk3368-geekbox.dtb"
BOOT_FDTFILE="rk3368-geekbox.dtb"
