# Rockchip RK3368 Geekbox
BOARD_NAME="Geekbox"
BOARDFAMILY="rockchip64"
BOOTCONFIG="geekbox_defconfig"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current,edge"

BOOT_SOC="rk3368"
BOOT_FDTFILE="rk3368-geekbox.dtb"
FDTFILE="rockchip/rk3368-geekbox.dtb"
BOOT_SCENARIO="trusted"

ATF_COMPILE="yes"

# Current branch uses v2022.07 for rockchip64 which causes u-boot.its error.
# We will provide our own patch to fix `cp: missing destination file operand after 'u-boot.its'`
# We must not ignore armbian u-boot patches so that the board boots successfully.
