# Rockchip RK3368 Geekbox
BOARD_NAME="Geekbox"
BOARDFAMILY="rockchip64"
BOOTCONFIG="geekbox_defconfig"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current,edge"

BOOT_SOC="rk3368"
BOOT_FDTFILE="rk3368-geekbox.dtb"
FDTFILE="rockchip/rk3368-geekbox.dtb"
BOOT_SCENARIO="blobless"

ATF_COMPILE="yes"
